{% set name = "nskeyedunarchiver" %}
{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9a2d5d48ea9e2c78d31bfbfc4a97c02794192f3b4548342d727d54bdd20beba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - NSKeyedUnArchiver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/avibrazil/NSKeyedUnArchiver
  summary: Decodes Apple's NSKeyedArchiver that were archived into text or binary plist files and returns a usable Python dict
  license: LGPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ickc
